using System.IO;
using Xunit;

namespace PCI.Compliance.Tests.Tests
{
    public class SBOMTests
    {
        [Fact(DisplayName = "SBOM file exists and is not empty (C.1)")]
        public void SBOM_FileExistsAndNotEmpty()
        {
            // Look for SBOM files generated by sbom-tool in the publish output
            var solutionRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
            var publishDir = Path.Combine(solutionRoot, "src", "WebApp", "bin", "Release", "net9.0", "publish", "_manifest", "spdx_2.2");
            var sbomFiles = Directory.Exists(publishDir)
                ? Directory.GetFiles(publishDir, "manifest.spdx.json", SearchOption.TopDirectoryOnly)
                : Array.Empty<string>();

            bool found = sbomFiles.Any(f => new FileInfo(f).Length > 0);
            Assert.True(found, $"No non-empty SBOM file found in expected sbom-tool output directory: {publishDir}");
        }
    }
}
